apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: staffjoy
spec:
  ports:
    - port: 3306
  selector:
    app: staffjoy
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: staffjoy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: staffjoy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: staffjoy
  template:
    metadata:
      labels:
        app: staffjoy
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
