apiVersion: apps/v1
kind: Deployment
metadata:
  name: companyserver-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: companyserver
  template:
    metadata:
      labels:
        app: companyserver
    spec:
      containers:
      - name: companyserver-container
        image: gcr.io/staffjoy-prod/companyserver:VERSION
        ports:
        - containerPort: 80
        - containerPort: 1000
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION # Gets replaced during deploy
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: sentry
              key: dsn
        - name: MYSQL_CONFIG
          valueFrom:
            secretKeyRef:
              name: company-mysql-stagings
              key: config
        - name: SIGNING_SECRET
          valueFrom:
            secretKeyRef:
              name: signing
              key: secret
        - name: SUITE_API_KEY
          valueFrom:
            secretKeyRef:
              name: suite
              key: apikey
