apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaccount-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: myaccount
  template:
    metadata:
      labels:
        app: myaccount
    spec:
      containers:
      - name: myaccount-container
        image: gcr.io/staffjoy-prod/myaccount:VERSION
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace