apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsserver-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: smsserver
  template:
    metadata:
      labels:
        app: smsserver
    spec:
      containers:
      - name: smsserver-container
        image: localhost:5000/smsserver:VERSION
        ports:
        - containerPort: 80
        - containerPort: 1000
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: TWILIO_SID
          value: S3CrEtApIkEy
        - name: TWILIO_TOKEN
          value: S3CrEtApIkEy
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
